// Code generated by MockGen. DO NOT EDIT.
// Source: ./core/matchRequest.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	core "github.com/hashcacher/ChessGoNeue/Server/v2/core"
	reflect "reflect"
)

// MockMatchRequests is a mock of MatchRequests interface
type MockMatchRequests struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRequestsMockRecorder
}

// MockMatchRequestsMockRecorder is the mock recorder for MockMatchRequests
type MockMatchRequestsMockRecorder struct {
	mock *MockMatchRequests
}

// NewMockMatchRequests creates a new mock instance
func NewMockMatchRequests(ctrl *gomock.Controller) *MockMatchRequests {
	mock := &MockMatchRequests{ctrl: ctrl}
	mock.recorder = &MockMatchRequestsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMatchRequests) EXPECT() *MockMatchRequestsMockRecorder {
	return m.recorder
}

// Store mocks base method
func (m *MockMatchRequests) Store(arg0 core.MatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store
func (mr *MockMatchRequestsMockRecorder) Store(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockMatchRequests)(nil).Store), arg0)
}

// FindAllMatchRequestsByUserId mocks base method
func (m *MockMatchRequests) FindAllMatchRequestsByUserId(userID int) []core.MatchRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllMatchRequestsByUserId", userID)
	ret0, _ := ret[0].([]core.MatchRequest)
	return ret0
}

// FindAllMatchRequestsByUserId indicates an expected call of FindAllMatchRequestsByUserId
func (mr *MockMatchRequestsMockRecorder) FindAllMatchRequestsByUserId(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllMatchRequestsByUserId", reflect.TypeOf((*MockMatchRequests)(nil).FindAllMatchRequestsByUserId), userID)
}

// FindMatchForUser mocks base method
func (m *MockMatchRequests) FindMatchForUser(userID int) core.MatchRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMatchForUser", userID)
	ret0, _ := ret[0].(core.MatchRequest)
	return ret0
}

// FindMatchForUser indicates an expected call of FindMatchForUser
func (mr *MockMatchRequestsMockRecorder) FindMatchForUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMatchForUser", reflect.TypeOf((*MockMatchRequests)(nil).FindMatchForUser), userID)
}

// ListenForGameCreatedNotify mocks base method
func (m *MockMatchRequests) ListenForGameCreatedNotify(userID int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForGameCreatedNotify", userID)
	ret0, _ := ret[0].(int)
	return ret0
}

// ListenForGameCreatedNotify indicates an expected call of ListenForGameCreatedNotify
func (mr *MockMatchRequestsMockRecorder) ListenForGameCreatedNotify(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForGameCreatedNotify", reflect.TypeOf((*MockMatchRequests)(nil).ListenForGameCreatedNotify), userID)
}

// NotifyGameCreated mocks base method
func (m *MockMatchRequests) NotifyGameCreated(userID int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyGameCreated", userID)
	ret0, _ := ret[0].(int)
	return ret0
}

// NotifyGameCreated indicates an expected call of NotifyGameCreated
func (mr *MockMatchRequestsMockRecorder) NotifyGameCreated(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyGameCreated", reflect.TypeOf((*MockMatchRequests)(nil).NotifyGameCreated), userID)
}

// Delete mocks base method
func (m *MockMatchRequests) Delete(id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *MockMatchRequestsMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMatchRequests)(nil).Delete), id)
}
