// Code generated by MockGen. DO NOT EDIT.
// Source: ./core/matchRequest.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	core "github.com/hashcacher/ChessGoNeue/Server/v2/core"
	reflect "reflect"
)

// MockMatchRequests is a mock of MatchRequests interface
type MockMatchRequests struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRequestsMockRecorder
}

// MockMatchRequestsMockRecorder is the mock recorder for MockMatchRequests
type MockMatchRequestsMockRecorder struct {
	mock *MockMatchRequests
}

// NewMockMatchRequests creates a new mock instance
func NewMockMatchRequests(ctrl *gomock.Controller) *MockMatchRequests {
	mock := &MockMatchRequests{ctrl: ctrl}
	mock.recorder = &MockMatchRequestsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMatchRequests) EXPECT() *MockMatchRequestsMockRecorder {
	return m.recorder
}

// Store mocks base method
func (m *MockMatchRequests) Store(arg0 core.MatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store
func (mr *MockMatchRequestsMockRecorder) Store(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockMatchRequests)(nil).Store), arg0)
}

// ListenForStore mocks base method
func (m *MockMatchRequests) ListenForStore() (core.MatchRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenForStore")
	ret0, _ := ret[0].(core.MatchRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenForStore indicates an expected call of ListenForStore
func (mr *MockMatchRequestsMockRecorder) ListenForStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForStore", reflect.TypeOf((*MockMatchRequests)(nil).ListenForStore))
}

// FindByUserID mocks base method
func (m *MockMatchRequests) FindByUserID(userID int) (core.MatchRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", userID)
	ret0, _ := ret[0].(core.MatchRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID
func (mr *MockMatchRequestsMockRecorder) FindByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockMatchRequests)(nil).FindByUserID), userID)
}

// FindAll mocks base method
func (m *MockMatchRequests) FindAll() ([]core.MatchRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]core.MatchRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockMatchRequestsMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMatchRequests)(nil).FindAll))
}

// Delete mocks base method
func (m *MockMatchRequests) Delete(id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *MockMatchRequestsMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMatchRequests)(nil).Delete), id)
}
